{
    'name': 'Digital Kamtibmas',
    'version': '19.0.1.0.0',
    'summary': 'Sistem Informasi Digital Kamtibmas Polrestabes Palembang',
    'description': 'Modul pengelolaan data kamtibmas digital untuk Polrestabes Palembang.',
    'category': 'Tools',
    'author': 'Cv Sel Studio',
    'website': 'https://selstudio.id',
    'depends': ['base', 'web', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/polsek_views.xml',
        'views/kabupaten_views.xml',
        'views/kecamatan_views.xml',
        'views/desa_views.xml',
        'views/eform_laka_views.xml',
        'views/antrian_views.xml',
        'views/loket_views.xml',
        'views/jenis_layanan_views.xml',
        'views/dashboard_views.xml',
        'views/display_config_views.xml',
        'views/antrian_display_template.xml',
        'views/konseling_views.xml',
        'views/rehab_views.xml',
        'views/barang_bukti_views.xml',
        'views/patroli_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # Libs
            'digital_kamtibmas/static/lib/leaflet/leaflet.css',
            'digital_kamtibmas/static/lib/leaflet/leaflet.js',
            # Markercluster: re-attach setelah leaflet agar tidak konflik dengan petadigi
            'digital_kamtibmas/static/lib/leaflet-markercluster/MarkerCluster.css',
            'digital_kamtibmas/static/lib/leaflet-markercluster/MarkerCluster.Default.css',
            'digital_kamtibmas/static/lib/leaflet-markercluster/leaflet.markercluster.js',
            'digital_kamtibmas/static/lib/echart/echarts.min.js',
            # Map widget
            'digital_kamtibmas/static/src/css/map_widget.css',
            'digital_kamtibmas/static/src/xml/map_widget.xml',
            'digital_kamtibmas/static/src/js/map_widget.js',
            # Dashboard
            'digital_kamtibmas/static/src/css/dashboard.css',
            'digital_kamtibmas/static/src/xml/dashboard.xml',
            'digital_kamtibmas/static/src/js/dashboard.js',
        ],
    },
    'installable': True,
    'application': True,
    'sequence': 2,
    'license': 'LGPL-3',
}
