from . import eform_laka
from . import yang_terlibat
from . import kabupaten
from . import kecamatan
from . import desa
from . import polsek
from . import jenis_layanan
from . import loket
from . import antrian
from . import display_config
from . import konseling
from . import rehab_tempat
from . import rehab
from . import barang_bukti
from . import patroli_grup
from . import patroli
from . import tahti_sel
from . import tahanan_kategori
from . import tahanan
from . import tahti_tamu
from . import tahti_kunjungan
from . import intelkam_wa_config
from . import intelkam_wa_group
from . import intelkam_distribusi
from . import intelkam_respon
from . import sertifikasi_soal
from . import sertifikasi_profil
from . import sertifikasi
from . import sertifikasi_peserta
from . import sertifikasi_cetak
from . import discuss_channel_patch
from . import notifikasi
from . import account_deletion_request
